### ISSUE TITLE
Screenshots attached in the bottom of the report

### ISSUE THREAD

**Issue by VinnieM** [trivago/cluecumber-report-plugin#141]
**Describe the bug**
When a screenshot (screenshot is taken in the After Scenario) is taken the screenshot is attached at the bottom of the report. Would it be possible to see the screenshot next to the step which failed?

Secondly To see the screenshot I need to click a button which says "_Show Before/After Hooks_" Can I have this changed to something like - _Show Screenshots_?

I am attaching the cucumber Json file along with the screenshots. 

In the first image you can see that the second step has an error. On the right-hand side, inside the Scenario Information, last line it says "_Hide Before/After Hooks_". By default when it loads up it shows as "_Show Before/After Hooks_". When I click on that button the screenshots are made visible in the bottom (after all the steps are completed). I'm guessing that since I have written attaching the screenshot inside the hooks, the Before and After hooks are shown.

<img width="1678" alt="Screen Shot 2019-03-11 at 5 21 09 PM" src="https://user-images.githubusercontent.com/3847873/54159091-85731780-4422-11e9-9f3d-dee0131f20e2.png">

The screenshot is attached at the bottom and is only visible if I click on "_Show Before/After Hooks_".
<img width="1679" alt="Screen Shot 2019-03-11 at 5 21 24 PM" src="https://user-images.githubusercontent.com/3847873/54159092-85731780-4422-11e9-9e45-14bd459d7d62.png">

This is the cucumber JSON file.
[cucumber-report.zip](https://github.com/trivago/cluecumber-report-plugin/files/2954261/cucumber-report.zip)

Please do let me know if I am doing anything wrong or if this is the expected behavior. 

PS: If I were to make some changes to this, would you be able to point me in the direction I would need to start looking.

**Comment by laxersaz** [comment]
This is the expected behavior. If your test framework attaches screenshots in an after hook, this will naturally be displayed in the after hooks section of Cluecumber.
If you want your screenshot to be displayed in the step where it failed, your framework has to handle this differently.
By the way, you can configure Cluecumber to pre-open the hooks sections for you so you don't have to click this button. See here: https://github.com/trivago/cluecumber-report-plugin/blob/master/README.md#expandbeforeafterhooks-expandstephooks-expanddocstrings
