### ISSUE TITLE
Screenshots not attached to the cluecumber html report on cucumber jvm parallel execution

### ISSUE THREAD

**Issue by nithingg** [trivago/cluecumber-report-plugin#181]
**Describe the bug**
I am using cucumber jvm 43.1, and executing the tests in parallel using the out of the box parallel support. I am using cluecumber to generate the test report after execution. However, the screenshots are not getting attached in the report. In the generated by default cucumber report, screenshots are attached.

I am executing via mvn clean verify.

POM.XML - Plugins

![POM-Plugins](https://user-images.githubusercontent.com/43971386/59638290-1ab54300-91ac-11e9-84cc-6c070a270dbd.PNG)

POM Dependencies

![Dependencies](https://user-images.githubusercontent.com/43971386/59638361-505a2c00-91ac-11e9-8404-4bcb53618226.PNG)

Please find below the screenshot of the cucumber json file.

![Capture](https://user-images.githubusercontent.com/43971386/59638189-d32eb700-91ab-11e9-8a89-d82a00d26156.PNG)

**Comment by laxersaz** [comment]
Are you automatically opening the after hooks in the report using the `<expandBeforeAfterHooks>true|false</expandBeforeAfterHooks>` property? Because if you don't, the hooks are closed and you need to press the 
![image](https://user-images.githubusercontent.com/5775857/59691075-c1b4d180-91e2-11e9-80c4-1a57fb81de81.png) button.

**Comment by nithingg** [comment]
@laxersaz Thanks for the quick reply. I missed the before after hooks button and configuration. 
Again thanks for the support.
