### ISSUE TITLE
Can we add some property in cluecucumber which will only show a specific tag execution?

### ISSUE THREAD

**Issue by goyalvipul** [trivago/cluecumber-report-plugin#265]
**Is your feature request related to a problem? 
Yes, this is a need of an hour. 
Automation testers tend to add multiple tags to a single scenario, which gets published in the report, as is.
This also duplicates the scenario count shown on the Scenario main page.
I want to show the report only for a particular tag which I actually executed.

**Describe the solution you'd like**
When we open the report it should only show the Scenarios executed under the mentioned tag.
"Scenario by Tag"

**Comment by laxersaz** [comment]
Hello @goyalvipul ,

I read your issue and also the discussion over at the karate repo. Still, I don't see the problem here.
If you want to execute scenarios that contain a specific test, it does not mean that all other tags should be hidden. Semantically they still belong to the executed scenario and should be displayed.

Do you have an example or some further explanation of what you mean?

**Comment by laxersaz** [comment]
There was no further answer/example given.
