### ISSUE TITLE
Add a new page to show a timeline of feature/scenarios that were executed

### ISSUE THREAD

**Issue by aritranayak** [trivago/cluecumber-report-plugin#81]
**Is your feature request related to a problem? Please describe.**
Problem in the sense that sometimes it is better to get a sequential view of the tests that were run in a numbered order, with the name of the method that got executed and whether it failed or passed or got skipped because of previous method(s) failing. This will help with understanding any gaps (like some missing steps) and a full picture view of what happened during the execution

**Describe the solution you'd like**
A separate page called 'Execution Timeline' where the Feature>Scenario numbered 1 to N will be listed with method names(s), status and available error message

**Describe alternatives you've considered**
Not considered any alternative apart from going through the logs

**Additional context**
Would like to contribute, if given the permission. Thanks in advance.

**Comment by laxersaz** [comment]
Hi @aritranayak ,

Can you clarify the look of such a page with an example? I'm not sure I completely get the intention.

Best,
Benjamin

**Comment by aritranayak** [comment]
@laxersaz I will try to create a mock-up and share the same at the earliest. Thanks for your patience.

**Comment by aritranayak** [comment]
Hi @laxersaz ,

  What I am trying to see is something like this:
   
![proposed mock-up](https://user-images.githubusercontent.com/12704424/44755333-938ec580-aada-11e8-91b4-ce8f42095131.png)

  The gray part is the Scenario which have the feature name just above it.
  The Scenarios can be expanded or collapsed by clicking on them. On expanding a scenario, we will get the steps available under them along with their pass or fail status etc.
   This will give us a picture of what happened during the test and if we need to make any change in the order of the scenarios etc. for better results; and for various other deductions. Let me know your views on this.

**Comment by laxersaz** [comment]
To be honest, I think having a page like this would transport the wrong idea. There should never be any dependency between scenarios let alone their execution order.
What could be done as a compromise is to expose the scenario index on the "All Scenarios" page tables so that it can be sorted by their order. This would keep the division into the three state tables, though (passed, failed, skipped).
It would be also possible to have a page called "Scenario Sequence" that shows this without dividing them into the three states (along the line of what you are suggesting). I wouldn't jam all steps into a view like this though - instead I would display it in one single table with links to all individual scenarios (as this is consistent with all other views).

**Comment by laxersaz** [comment]
Ready for release in 1.4.0
